Adding report deployment step template.
OctopusDeploy/Library pull request #1008
Opened 2020-09-22 21:27 UTC by harbertc

### Step template checklist

- [X] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [X] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [X] Parameter names should not start with `$`
- [X] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [X] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [N/A] If a new `Category` has been created:
   - [N/A] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [N/A] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

2020-09-22 21:52 UTC, twerthi commented
Thank you for your submission :)  Would you be able to add something that checks to make sure pip is installed and reports an error if it is not?

2020-09-29 12:40 UTC, harbertc commented
@twerthi I added the following which should provide a nicer message if pip is not available. Please let me know if this is what you had in mind.

```
try {$pipCmd = get-command pip} catch {}
if (!($pipCmd)) {
	Fail-Step "This step template requires Python 3.6 or greater and pip to be installed. Python is available at https://www.python.org/downloads/"
}
```

2020-09-29 13:03 UTC, harrisonmeister requested changes
One minor change to revert the Id of `testery-create-test-run` and I think you are good to go!

2020-09-29 13:07 UTC, harbertc commented on step-templates/testery-create-test-run.json
> +  "Id": "ed901ef2-9799-4f29-90c0-e1a8e6d92a2c",
@harrisonmeister - Done. Used a new instance of Octopus to generate the new step template and that was auto-generated. I've set it back.

2020-09-29 13:15 UTC, harrisonmeister approved these changes

2020-09-29 13:15 UTC, merged