Improved handling of Jenkins queue handling of no credential use case.
OctopusDeploy/Library pull request #1281
Opened 2022-07-05 16:44 UTC by brianpendell

Added NULL check to authorization procedure; script as written will bypass credential operations if the username is empty string -- but a null user string (which is what you get if you don't set the parameter box) is NOT an empty string.  The test will pass and cause a failure because the username is nonexistent.

Changed
if ($jenkinsUserName -ne \"\")
to
if (($jenkinsUserName -ne \"\") -and (-not ($jenkinsUserName -eq $null)))

---

### Step template checklist

[X ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000` = Existing step template / N/A
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [X ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ X] Parameter names should not start with `$`
- [ X] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [X ] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ X] If a new `Category` has been created: - No Category/ N/A.

2022-07-05 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OctopusDeploy/Library?pullRequest=1281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OctopusDeploy/Library?pullRequest=1281) before we can accept your contribution.<br/><hr/>**Brian Pendell** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OctopusDeploy/Library?pullRequest=1281) it.</sub>

2022-07-06 12:58 UTC, coryreid requested changes
Hey @brianpendell , thanks again for the submission!

One minor request - can you refactor your if statement to take advantage of the string class `IsNullOrWhitespace` helper method?

From
```
if (($jenkinsUserName -ne "") -and (-not ($jenkinsUserName -eq $null)))
```

To
```
if (![string]::IsNullOrWhiteSpace($jenkinsUserName))
```

I know it seems minor, but the added readability (and consistency with other places where we check this same sort of logic) is helpful!

2022-07-06 14:46 UTC, brianpendell commented
Okay, @coryreid . I've tested that change and it seems to work. So I've committed the isnullorwhitespace refactoring that you've asked for.  Your changes are now in place so I think we're ready whenever you are.

2022-07-06 15:01 UTC, coryreid approved these changes
Thanks for updating this @brianpendell , it's appreciated!

2022-07-06 15:01 UTC, merged