Update iis-bindings-restore.json
OctopusDeploy/Library pull request #1326
Opened 2023-01-30 20:03 UTC by krusoleo

We found an issue with the IIS Bindings Restore Step Template.
It does not restore a star binding "*:443:*" or "*:80:*" that was previously backed up by the IIS Bindings Backup Step Template.
The error is in line 74 of the powershell script:
`$existing = Get-WebBinding -Name $webSiteName -Protocol $binding.protocol -IPAddress $bindingArray[0] -Port $bindingArray[1] -HostHeader $bindingArray[2]`
which returns all existing bindings for the site - even though the star binding does not exist - because the -HostHeader parameter is set to "*". This results in the star binding not being restored.

This fix is to check existing bindings by comparing the whole bindingInformation string instead of the 3 parameters specifically:
`$existing = Get-WebBinding -Name $webSiteName -Protocol $binding.protocol | Where-Object { $_.bindingInformation -eq $binding.bindingInformation }`

This fix will restore star bindings and all other bindings as well

2023-01-30 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OctopusDeploy/Library?pullRequest=1326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OctopusDeploy/Library?pullRequest=1326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OctopusDeploy/Library?pullRequest=1326) it.</sub>

2023-02-06 17:59 UTC, bstr413 approved these changes

2023-02-06 18:04 UTC, bstr413 requested changes

2023-02-06 18:04 UTC, bstr413 commented on step-templates/iis-bindings-restore.json
> +  "Id": "bf7bc5d6-7576-43e6-8306-5e9e15cbab6a",
From the Step Template Checklist:

NOTE If you are modifying an existing step template, please make sure that you do not modify the Id property (updating the Id will break the Library sync functionality in Octopus).

```suggestion
  "Id": "9d357886-1896-4240-a89f-118c7ca8ec05",

```

2023-02-09 20:01 UTC, merged

2023-02-10 14:31 UTC, krusoleo commented
np :) happy to contribute