Step Template: .NET Core - Install .NET Core Framework
OctopusDeploy/Library pull request #1361
Opened 2023-05-16 11:57 UTC by dandraka

### Step template checklist

- [X] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [X] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [X] Parameter names should not start with `$`
- [X] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [X] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [X] If a new `Category` has been created:
   - [X] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [X] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

2023-05-23 23:25 UTC, jbristowe commented on step-templates/windows-install-net-core-framework.json
> +  "Description": "Installs .Net Core runtime or SDK using the [Microsoft install script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).",
```suggestion
  "Description": "Installs the .NET Core runtime or SDK using the [Microsoft install script](https://learn.microsoft.com/dotnet/core/tools/dotnet-install-script).",
```

2023-05-23 23:25 UTC, jbristowe commented on step-templates/windows-install-net-core-framework.json
> +      "Label": ".Net Install Location",
```suggestion
      "Label": ".NET Install Location",
```

2023-05-23 23:26 UTC, jbristowe commented on step-templates/windows-install-net-core-framework.json
> +      "Label": ".Net Build Quality",
```suggestion
      "Label": ".NET Build Quality",
```

2023-05-23 23:26 UTC, jbristowe commented on step-templates/windows-install-net-core-framework.json
> +      "HelpText": "If true, installs .Net runtime.\nIf false, installs .Net SDK.",
```suggestion
      "HelpText": "If true, installs .NET runtime.\nIf false, installs .NET SDK.",
```

2023-06-15 16:14 UTC, twerthi requested changes
Greetings dandraka!  Apologies for the delay in reviewing, will try to get it pushed through faster.  I did have some changes
1.  Namespace the Parameter names to avoid variable name collision (ie change RuntimeOnly to something like Template.RuntimeOnly)
2.  Variables in Octopus are all Text, line 15 of the PowerShell is checking a boolean value, try converting it to an actual boolean value or update the If to check for the text value of True

2023-06-16 06:44 UTC, dandraka commented
Thanks for the suggestions, I see now I forgot to namespace the parameters
indeed --shame on me, it's on the checklist. I'll do it in the next few
days. And I'll make the types more concrete as well.

Kind regards / Freundliche Grüsse / Un saludo cordial / Met vriendelijke
groeten / भवदीय / Με φιλικούς χαιρετισμούς

Jim (Dimitrios) Andrakakis
Scrum master /
Senior
s
oftware
e
ngineer


Στις Πέμ 15 Ιουν 2023 στις 6:14 μ.μ., ο/η Shawn Sesna <
***@***.***> έγραψε:

> ***@***.**** requested changes on this pull request.
>
> Greetings dandraka! Apologies for the delay in reviewing, will try to get
> it pushed through faster. I did have some changes
>
>    1. Namespace the Parameter names to avoid variable name collision (ie
>    change RuntimeOnly to something like Template.RuntimeOnly)
>    2. Variables in Octopus are all Text, line 15 of the PowerShell is
>    checking a boolean value, try converting it to an actual boolean value or
>    update the If to check for the text value of True
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OctopusDeploy/Library/pull/1361#pullrequestreview-1481972848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB2YKD4B2WR2ZA4MLWUNILXLMYFLANCNFSM6AAAAAAYDRDEGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-19 05:28 UTC, domenicsim1 approved these changes

2023-06-28 17:42 UTC, twerthi commented
@dandraka Have you made the updates?

2023-12-05 22:42 UTC, twerthi commented
Closing PR due to inactivity.

2023-12-05 22:42 UTC, closed without merging